CREATE TABLE `cus_info` (
  `id` int unsigned not null AUTO_INCREMENT,
  `order_time` bigint(20) not null default 0,
  `pay_time` bigint(20) not null default 0,
  `submit_time` bigint(20) not null default 0,
  `ship_time` bigint(20) not null default 0,
  `refund_time` bigint (20) not null default 0,
  `print_time` bigint(20) not null default 0,
  `pick_order_time` bigint(20) not null default 0,
  `cus_acc` varchar(64) not null default '',
  `cus_name` varchar(64) not null default '',
  `cus_email` varchar(64) not null default '',
  `recv_name` varchar(64) not null default '',
  `recv_company` varchar(64) not null default '',
  `recv_tax_no` varchar(64) not null default '',
  `recv_addr_no` varchar(64) not null default '',
  `addr_detail` text,
  `addr1` text,
  `addr2` text,
  `addr1plus2` text,
  `recv_city` varchar(64) not null default '',
  `recv_state` varchar(64) not null default '',
  `postcode` varchar(64) not null default '',
  `country` varchar(64) not null default '',
  `country_cn` varchar(64) not null default '',
  `country_code` varchar(64) not null default '',
  `phone` varchar(64) not null default '',
  `cellphone` varchar(64) not null default '',
  `sku` text,
  `prod_id` text,
  `prod_name` text,
  `prod_price` varchar(64) not null default '',
  `prod_num` varchar(64) not null default '',
  `prod_mod` text,
  `pic_url` text,
  `source_url` text,
  `sale_url` text,
  `multi_prod_name` text,
  `pay_method` varchar(128) not null default '',
  `currency` varchar(128) not null default '',
  `order_price` float not null default 0,
  `ship_fee` float not null default 0,
  `refund` float not null default 0,
  `est_profit` float not null default 0,
  `cost_profit_rate` float not null default 0,
  `sale_profit_rate` float not null default 0,
  `est_ship_fee` float not null default 0,
  `pkg_no` varchar(64) not null default '',
  `order_no` varchar(64) not null default '',
  `tx_no` text,
  `order_status` varchar(64) not null default '',
  `platform` varchar(64) not null default '',
  `shop_acc` varchar(64) not null default '',
  `order_comment` text,
  `pick_comment` varchar(64) not null default '',
  `cus_service_comment` varchar(64) not null default '',
  `refund_reason` varchar(64) not null default '',
  `order_tag` varchar(64) not null default '',
  `order_label` varchar(64) not null default '',
  `appoint_ship` text,
  `ship_method` varchar(64) not null default '',
  `ship_no` varchar(64) not null default '',
  `ship_order` varchar(64) not null default '',
  `weight` float not null default 0,
  `cn_clearance_name` varchar(64) not null default '',
  `en_clearance_name` varchar(128) not null default '',
  `clearance_price` varchar(64) not null default '',
  `clearance_weight` float not null default 0,
  `clearance_no` varchar(64) not null default '',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
